# The version of the docs
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # TODO: remove after testing
  fail_on_warning: true

python:
  install:
    - method: pip
      path: . 
    - requirements: requirements.txt
